apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: activityservice
spec:
  selector:
    matchLabels:
      app: activityservice
  serviceName: activityservice
  replicas: 1
  template:
    metadata:
      labels:
        app: activityservice
        istio-injection: "enabled"
    spec:
      containers:
        - name: "activityservice"
          image: "chirper/activity-stream-impl"
          imagePullPolicy: "Never"
          resources:
            requests:
              memory: "512Mi"
          ports:
            - containerPort: 9000
              name: "http-lagom-api"
          env:
            - name: "APPLICATION_SECRET"
              value: "{{ .Values.temp.secret }}"
            - name: "ACTIVITYSERVICE_BIND_PORT"
              value: "9000"
            - name: "ACTIVITYSERVICE_BIND_IP"
              value: "0.0.0.0"
          readinessProbe:
            httpGet:
              path: "/_status/circuit-breaker/current"
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 5
