apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "web" #{{ template "first-stab.fullname" . }}
  labels:
    app: "web" #{{ template "first-stab.name" . }}
    chart: {{ template "first-stab.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: web
  serviceName: web
  replicas: 1
  template:
    metadata:
      labels:
        app: web
        istio-injection: "enabled"
    spec:
      containers:
        - name: web
          image: chirper/front-end
          imagePullPolicy: "Never"
          resources:
            requests:
              memory: "512Mi"
          ports:
            - containerPort: 9000
          env:
            - name: "APPLICATION_SECRET"
              value: "{{ .Values.temp.secret }}"
            - name: "WEB_BIND_PORT"
              value: "9000"
            - name: "WEB_BIND_IP"
              value: "0.0.0.0"
          readinessProbe:
            httpGet:
              path: "/"
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 5
